server {
    listen 8001;
    server_name _;
    root /var/www/fire_calc;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}
